import requests
from ollama import chat
from ollama import ChatResponse
from dotenv import load_dotenv
import os
import logging

# Set up logging
SRC_DIR = os.path.dirname(os.path.abspath(__file__))
APP_DIR = os.path.dirname(SRC_DIR)
log_file = os.path.join(APP_DIR, 'daily-motivation.log')
logging.basicConfig(
    filename=log_file,
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)

load_dotenv()
webhook_url = os.getenv("DISCORD_WEBHOOK_URL")
model_name = os.getenv("OLLAMA_MODEL")

response: ChatResponse = chat(model=model_name, messages=[
  {
    'role': 'user',
    'content': 'Generate a single, short, motivational statement to be read by a user when they first wake up in the morning. Respond only with the motivational quote.',
  },
])
motivation_quote = response['message']['content']
logging.info(f"Motivational quote generated by {model_name}: {motivation_quote}")

# Post message on Discord
requests.post(
    webhook_url,
    json={"content": motivation_quote}
)
logging.info(f"Successfully posted message '{motivation_quote}' to discord via webhook {webhook_url}")

